#!/bin/env/ bash

# Terminal
sudo apt-get install -y rxvt-unicode-256color
sudo apt-get install -y tmux

# System admin tools
sudo apt-get install -y parted
sudo apt-get install -y gparted
sudo apt-get install -y ranger
sudo apt-get install -y nemo
sudo apt-get install -y dunst
sudo apt-get install -y rofi
sudo apt-get install -y neofetch

# Tools
sudo apt-get install -y wget
sudo apt-get install -y tree
sudo apt-get install -y entr
sudo apt-get install -y sshfs
sudo apt-get install -y youtube-dl
sudo apt-get install -y wireshark
sudo apt-get install -y gnucash
sudo apt-get install -y keepassxc
sudo apt-get install -y redshift
sudo apt-get install -y inkscape
sudo apt-get install -y highlight
sudo apt-get install -y moreutils
sudo apt-get install -y xclip
sudo apt-get install -y screen
sudo apt-get install -y ipython3
sudo apt-get install -y rlwrap
sudo apt-get install -y espeak

# ZSH
sudo apt-get install -y zsh
chsh -s $(which zsh)
sudo apt-get install -y fonts-powerline

# Hugo
sudo apt-get install -y hugo
sudo apt-get install -y python3-pygments

# Programmer
sudo apt-get install -y build-essential
sudo apt-get install -y automake autoconf libtool
sudo apt-get install -y g++
sudo apt-get install -y exuberant-ctags
sudo apt-get install -y global
sudo apt-get install -y doxygen
sudo apt-get install -y texlive-full
sudo apt-get install -y picocom
sudo apt-get install -y graphviz

# Git
sudo apt-get install -y git

# Emacs
sudo apt-get install -y emacs

# Embedded
sudo apt-get install -y i2c-tools
sudo apt-get install -y ser2net
sudo apt-get install -y gpiod

# Mocking
sudo apt-get install -y ser2net
sudo apt-get install -y gpiod
sudo apt-get install -y i2c-tools

# Qemu
sudo apt-get install -y qemu

# Python
sudo apt-get install -y python3-setuptools
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-serial
sudo apt-get install -y python3-pygments
sudo apt-get install -y python3-jedi

# SDL2
sudo apt-get install -y libsdl2-dev
sudo apt-get install -y libsdl2-image-dev
sudo apt-get install -y libsdl2-ttf-dev
sudo apt-get install -y libsdl2-mixer-dev

# Virtualbox
sudo apt-get install -y virtualbox
sudo apt-get install -y virtualbox-qt
sudo apt-get install -y virtualbox-guest-additions-iso

# Ricing
sudo apt-get install -y feh
sudo apt-get install -y imagemagick
pip3 install --user pywal
