#!/usr/bin/env bash

TARGET_DIR="${HOME}/opt/"

# Make dir if it doesn't exist
mkdir -p ${TARGET_DIR}

# Download
git clone git://github.com/cpputest/cpputest.git ${TARGET_DIR}

# Go to build dir
cd ${TARGET_DIR}

# Build
./autogen.sh
mkdir a_build_dir && cd a_build_dir
../configure
make
make check

exit 0
