#!/usr/bin/env bash

MIRROR="ftp.cc.uoc.gr/mirrors/gnu/emacs/"
TAR="emacs-27.2.tar.xz"
OUTPUT_PATH="/tmp/emacs/"

#############################################
# Do not touch bellow this line

# Dependencies
sudo apt-get install -y libgtk-3-dev
sudo apt-get install -y libxpm-dev libjpeg-dev libgif-dev libtiff-dev
sudo apt-get install -y libgnutls28-dev
sudo apt-get install -y libtinfo-dev
sudo apt-get install -y libncurses5-dev

# Download bleeding-edge emacs
wget ${MIRROR}${TAR} -P ${OUTPUT_PATH}

# Untar
cd ${OUTPUT_PATH}
tar -xJf ${TAR}

# Go to build dir
FILENAME=$(basename -- "${OUTPUT_PATH}${TAR}")
FILENAME="${FILENAME%.*}"
FILENAME="${FILENAME%.*}"
cd ${FILENAME}

# Build and install
./autogen.sh
./configure
make
sudo make install

# Clean
rm -rf ${OUTPUT_PATH}

# Notify user
echo "Done"
