#!/usr/bin/env bash

# Fix Java GUIs
# https://wiki.archlinux.org/index.php/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing
wmname LG3D

# Workspaces
bspc monitor -d "Idle" "Work" "Dev" "Net" "Extra"

# Gaps amd borders
BORDER=1
GAP=6
bspc config border_width           ${BORDER}
bspc config window_gap             ${GAP}
bspc config top_padding            -${GAP}
bspc config bottom_padding         -${GAP}
bspc config left_padding           -${GAP}
bspc config right_padding          -${GAP}

# Misc
#bspc config split_ratio           0.62
bspc config split_ratio            0.55

# Mouse
bspc config focus_follows_pointer  false
bspc config click_to_focus         button1
#bspc config pointer_follows_focus true

# Borders
bspc config normal_border_color    "#272822"
bspc config focused_border_color   "#a6e22e"
bspc config active_border_color    "#f92672"

# Monocle
bspc config single_monocle         true
bspc config borderless_monocle     true
bspc config paddingless_monocle    false
bspc config gapless_monocle        false

# Remove old rules on reset
bspc rule -r "*"

# Rules
#bspc rule -a Firefox     desktop='^4'
#bspc rule -a Thunderbird desktop='^5'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Unknown
#bspc config automatic_scheme "longest_side"

# Trayer
pgrep -x trayer > /dev/null && pkill -x trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut false --width 3 --transparent true --alpha 0 --tint 0x272822 --height 15 &

# We wait until the trayer loads
until trayer_id=$(xdo id -a 'trayer'); do
    sleep 1s
done

# Put the trayer one layer below
# This solves fullscreen of other windows
for id in $trayer_id
do
    xdo below -t "$(xdo id -n root)" "${id}"
done

# New lemonbar
~/.config/bspwm/lemonSqueezer &

# Compton
pgrep -x compton > /dev/null && pkill -x compton
compton --config ~/.config/compton/compton.conf &

# Notification system
pgrep -x dunst > /dev/null && pkill -x dunst
dunst &
